### ISSUE TITLE
escudos

### ISSUE THREAD

**Issue by paulolima789** [tiagobrilhante/spaceshooter#5]
![image](https://github.com/tiagobrilhante/spaceshooter/assets/106263993/b13ffcc5-f7d1-4ee8-bb82-5dcaa8a462c7)

durante o pause e possivel usar os escudos.

**Comment by tiagobrilhante** [comment]
parcialemente resolvido.
ainda falta a questão de  durante o pause, parar a animação no index correto

**Comment by tiagobrilhante** [comment]
Esse está sendo um pouco mais complexo pois a ógica empregada usava o sprite_speed para ativar o escudo....
vou ter que repensar a lógica inteira do escudo
